CREATE TABLE yatzy.yatzy
(
	id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
	antall INTEGER,
	brett VARCHAR,
	PRIMARY KEY (id)
);

CREATE TABLE yatzy.yatzy
(
	id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
	antall INTEGER,
	brett VARCHAR,
	PRIMARY KEY (id)
);